<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Tag extends Model
{
    use HasFactory;

    //  only the 'name' attribute of the Tag model can be mass assigned.
    protected $fillable = ['name'];

    // The slug attribute will be automatically generated when a new tag is created.
    // The slug will be generated by converting the name attribute to a URL friendly string.
    public static function boot()
    {
        // This is from lifecycle hooks in Laravel
        parent::boot();

        // When a new tag is being created, the slug will be generated from the name attribute.
        static::creating(function ($tag) {
            $tag->slug = Str::slug($tag->name);
        });
    }

    public function taggables()
    {
        return $this->morphedByMany('App\Models\Taggable', 'taggable');
    }
}